const user = {
    username: 'nvduong1',
    name: 'Administrator',
    email: 'nvduong1@cmc.com.vn',
    birthday: '20/01/2021',
    gender: 'Nam',
    position: '',
    startWork: '21/09/2022',
    phoneNumber: '0123456789',
    leaderName: 'Administrator',
    leaderEmail: 'abc@gmail.com',
    skype: '',
    facebook: '',
    school: '',
    literacy: '',
    degree: '',
    permanent_address: '',
    temporary_address: '',
    idNumber: '',
    placeForID: '',
    dateForID: '',
    LatePerMonth: 0,
    LatePerYear: 0,
}

export default user;